# Generated by Django 2.0 on 2018-01-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuln',
            name='v_fin',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
