# Generated by Django 2.0 on 2018-01-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180102_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuln',
            name='v_ids',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='vuln_text',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
