# Generated by Django 2.0 on 2018-01-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20180116_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuln',
            name='v_con',
            field=models.CharField(default='NONE', max_length=9000),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='v_dis',
            field=models.CharField(default='NONE', max_length=9000),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='v_fix',
            field=models.CharField(default='NONE', max_length=9000),
        ),
    ]
