# Generated by Django 2.0 on 2018-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_vuln_v_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuln',
            name='v_command_enabled',
            field=models.CharField(default='NONE', max_length=9000),
        ),
        migrations.AddField(
            model_name='vuln',
            name='v_command_status',
            field=models.CharField(default='NONE', max_length=9000),
        ),
    ]
