# Generated by Django 2.0.1 on 2018-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20180117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuln',
            name='v_con',
            field=models.CharField(default='NONE', max_length=10000),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='v_dis',
            field=models.CharField(default='NONE', max_length=10000),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='v_fix',
            field=models.CharField(default='NONE', max_length=10000),
        ),
    ]
