# Generated by Django 2.0.1 on 2018-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20180120_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuln',
            name='v_remove_fix',
            field=models.CharField(default='NONE', max_length=9000),
        ),
    ]
