# Generated by Django 2.0 on 2018-01-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
